### ISSUE TITLE
Use OpenNI2 with Kinect on Linux

### ISSUE THREAD

**Issue by josuerocha** [occipital/OpenNI2#103]
Can anybody please help me to install and use OpenNI2 with Kinect on Linux? I have compiled openni2, but it seems like the installer does not place the files in the lib directories, therefore I am not able to use it in other applications.

Please help. Thanks in advance.

**Comment by s0r2637** [comment]
Maybe follow these set of instructions.

http://matrivian.github.io/computer%20vision/2015/04/07/openni2-2-and-nite2-2-on-ubuntu-14-04-lts.html

Hope it helps you.

**Comment by rickyzhang82** [comment]
@s0r2637 The link is dead.

The packaging script failed as well
```
[Ricky@t20 Packaging]$ pwd
/home/Ricky/repo/github/OpenNI2/Packaging
[Ricky@t20 Packaging]$ ./ReleaseVersion.py x64
Creating installer for OpenNI 2.2 x64
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib64/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2
```
