### ISSUE TITLE
Problem when run 'ReleaseVersion.py': subprocess.CalledProcessError:

### ISSUE THREAD

**Issue by haohaokeyan** [occipital/OpenNI2#135]
It's just the install process. After 'make', I gave the Command, as the 'readme' tells: `sudo ./ReleaseVersion.py x64.`
Then information get:
`Creting installer for OpenNI 2.2 x64
Traceback (most recent call last):
   File "./ReleaseVersion.py", line 166, in <module>
      subprocess.check_call(['make', '-C', '../', '-j'+calc_jobs_number(), 'PLATFORM=' + plat, 'clean'], stdout=devNull, stderr=devNull)
   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
      raise CalledProcessError(retcode, cmd)
subprocess.CallProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'clean']' returned non-zero exit status 2`

Anyone knows the possible reason?

**Comment by totovr** [comment]
You must run:

        python2 ReleaseVersion.py x64

I compiled 5 minutes ago and it worked creating inside of final:

       ~/Final/OpenNI-Linux-x64-

> Note that I already unpacked the file OpenNI-Linux-x64-.tar.bz2

**Comment by haohaokeyan** [comment]
@totovr I did what you suggested, but still the problem keeps the same. I just don't understand what the problem actually is.

**Comment by haohaokeyan** [comment]
@totovr Ubuntu 14.04. So what do you think the problem lies?
Actually I just removed these:

`Packaging/Harvest.py lines 314-315 The ones where it says #Documentation`
`Source/Documentation/Runme.py lines 49-50 something about javadoc_error`(this is where 'make' error lies)

Then the installer can be generated. But I am not sure if the problem is solved properly.

**Comment by totovr** [comment]
Is easier doing by this way [KinectV2](https://github.com/totovr/KinectV2)
