### ISSUE TITLE
sudo ./ReleaseVersion.py x64 error

### ISSUE THREAD

**Issue by sunglyoungKim** [occipital/OpenNI2#136]
Creating installer for OpenNI 2.2 x64
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2

Hello, I am using linux 18.04 beta version. when I do "sudo ./ReleaseVersion.py x64" I got the error.
what should I do?

**Comment by HWiese1980** [comment]
Confirmed. Seems like this repo is dead.
