### ISSUE TITLE
OpenNI2-kinect2/Packaging error running ReleaseVersion.py x64

### ISSUE THREAD

**Issue by skymeson** [occipital/OpenNI2#80]
I'm using the OpenNI2-kinect2

It builds from the root directory

cd /home/skymeson/kinect/OpenNI2-kinect2
make 

No problems so far.

cd Packaging
sudo ./ReleaseVersion.py x64

And then I get errors.

Creating installer for OpenNI 2.3 x64
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 200, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2

Could be my setup but I figured I'd open an issue in case others were having the same problem.

**Comment by jselikof** [comment]
@skymeson which host platform are you building on?

**Comment by willydlw** [comment]
If you are running this under Linux, try sudo ./ReleaseVersion.py x64

**Comment by jselikof** [comment]
@willydlw,  running ./ReleaseVersion.py as root will create a temp directory owned by root, which would cause a problem if later run not as root.

@skymeson, check build.release.x64.log to determine the cause of the failure.

**Comment by keikurono** [comment]
I have the same problem.... could anyone fixed it?

**Comment by rossanag** [comment]
Same problem, these are the errors related to python in these errors:
When running **make**
```
1-   ```
File "Source/Documentation/Runme.py", line 50, in <module>
    subprocess.check_call(cmd, stdout=open(os.devnull,"w"), stderr=open(errfile,"w"))
  File "/usr/lib/python3.2/subprocess.py", line 489, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['javadoc', '-d', 'java', '../../Wrappers/java/OpenNI.java/src/org/openni/Recorder.java', '../../Wrappers/java/OpenNI.java/src/org/openni/CropArea.java', '../../Wrappers/java/OpenNI.java/src/org/openni/CoordinateConverter.java', '../../Wrappers/java/OpenNI.java/src/org/openni/NativeMethods.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Version.java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoStream.java', '../../Wrappers/java/OpenNI.java/src/org/openni/PlaybackControl.java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoFrameRef.java', '../../Wrappers/java/OpenNI.java/src/org/openni/ImageRegistrationMode.java', '../../Wrappers/java/OpenNI.java/src/org/openni/OutArg.java', '../../Wrappers/java/OpenNI.java/src/org/openni/VideoMode.java', '../../Wrappers/java/OpenNI.java/src/org/openni/SensorInfo.java', '../../Wrappers/java/OpenNI.java/src/org/openni/DeviceInfo.java', '../../Wrappers/java/OpenNI.java/src/org/openni/SensorType.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Device.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Point2D.java', '../../Wrappers/java/OpenNI.java/src/org/openni/OpenNI.java', '../../Wrappers/java/OpenNI.java/src/org/openni/Point3D.java', '../../Wrappers/java/OpenNI.java/src/org/openni/PixelFormat.java']' returned non-zero exit status 1
make: *** [doc] Error 1

```
2- when running **ReleaseVersion.py**
```

python ReleaseVersion.py x64
Creating installer for OpenNI 2.2 x64
Traceback (most recent call last):
  File "ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2

**Comment by ItaySharon** [comment]
same problem here, log:
`OSError: [Errno 2] No such file or directory: '/home/user/OpenNI2/Source/Documentation/html'
Makefile:157: recipe for target 'release' failed
make: *** [release] Error 1`

**Comment by AlexMetsai** [comment]
There is a dependency on Doxygen. So just sudo apt-get doxygen and then run the ReleaseVersion.py

**Comment by vladsterz** [comment]
There is a dependency on doxygen. Just sudo apt-get doxygen and then run ReleaseVersion.py
