### ISSUE TITLE
Issue running ReleaseVersion.py

### ISSUE THREAD

**Issue by physincubus** [occipital/OpenNI2#86]
When I run `./ReleaseVersion.py x64` I get the following output:

`Creating installer for OpenNI 2.2 x64
Traceback (most recent call last):
  File "./ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2`

Followed by an empty 'Final' Directory. Don't know what this means. looked through the issues and didn't see anyone else with this issue. Any idea what it means?

**Comment by aicioara** [comment]
Had the same issue. Solved it by removing the following lines

```
Packaging/Harvest.py lines 315-316 The ones where it says #Documentation
Source/Documentation/Runme.py lines 31-32 Something about Temp/doxygen_error
```

I can't really track down what is happening. I think mkdir fails or something along those lines. Should definitely be fixed.

**Comment by aicioara** [comment]
I believe it's because I don't have doxygen installed. 

for you: `sudo apt-get install doxygen`

For @ntisserand add checker in the installer. If doxygen is not installed, skip doc building. Alternatively add a note.

**Comment by jselikof** [comment]
@physincubus is the problem resolved after installing doxygen?

**Comment by aicioara** [comment]
@jselikof I believe the issue should be solved by the maintainers. A check whether or not `doxygen` is installed and skip building documentation should be trivial to do and would ensure that further users will not be affected by this issue in the future.

Given that Linux distros do not usually come with doxygen installed, the assumption that it exists will not hold in general.

**Comment by jselikof** [comment]
@physincubus check build.release.x64.log in the Packaging directory. The root cause should be clear from the log.
@aicioara not arguing that doxygen isn't part of the distro, but it's not likely that it will become unavailable.  Let's find out the root cause and go from there.

**Comment by ashokbugude** [comment]
Facing the same issue

**Comment by aicioara** [comment]
@ashokbugude Did any of the solutions above work?

**Comment by rossanag** [comment]
@aicioara  although I had doxigen installed I faced the same issue, I tryed what you suggested by commenting the lines and the same error occurs when running `python Releaseversion.py x64`:

```
Traceback (most recent call last):
  File "ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 511, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2
rossana@Studio:~/OpenNI2/Packaging$ 

Did anyone try something different to solve it?
Ubuntu 12.04 64 bits.
```

**Comment by rossanag** [comment]
Well improving step by step, I could get the installer, but the lines I had to comment were the last ones in Runme.py, precisely it seems it needed a workaround in linux which doesn't work:

# workaround a strange linux behavior where you must pass the list of files 
# the following lines were commented:
cmd = [javaDocExe, '-d', 'java']
for root, dirs, files in os.walk(javaSrc):
     for file in files:
         cmd.append(os.path.join(root, file))

 errfile = "Temp/javadoc_error"
# subprocess.check_call(cmd, stdout=open(os.devnull,"w"), stderr=open(errfile,"w"))

**Comment by mozi22** [comment]
Anybody resolved this issue ?

**Comment by aicioara** [comment]
Not sure if it was solved on `master`, but my suggestion definitely did the trick for me.

**Comment by mozi22** [comment]
yeah, your solution worked for me too. Thanks.

**Comment by Jsalies** [comment]
I'm facing a similar issue. I'm on Ubuntu 16.04.

I tried to comment lines like some of us tried but it didn't work.
All dependencies are installed.
I'm still searching the issue.

here is the error : 
  File "ReleaseVersion.py", line 170, in <module>
    subprocess.check_call(['make', '-C', '../', '-j' + calc_jobs_number(), 'PLATFORM=' + plat, 'release'], stdout=buildLog, stderr=buildLog)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-C', '../', '-j2', 'PLATFORM=x64', 'release']' returned non-zero exit status 2

**Comment by haohaokeyan** [comment]
Facing the same problem. aicioara 's trick inspired me though failing to solve the problem. I just concentrate on the error information in the log of `make`, it should be raised by `subprocess`. Find the code then remove it as aicioara said. For me it is:
`Source/Documentation/Runme.py lines 49-50 something about javadoc_error`
remove this too:
`Packaging/Harvest.py lines 314-315 The ones where it says #Documentation`

I'm not sure if the problem is solved properly, but it did work.
